"""Change password

Revision ID: 18c26bbd99e4
Revises: a2fa5795f444
Create Date: 2026-02-16 22:08:55.723355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18c26bbd99e4'
down_revision: Union[str, Sequence[str], None] = 'a2fa5795f444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=48),
               type_=sa.String(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=48),
               existing_nullable=False)
    # ### end Alembic commands ###
