"""Added subsctiption table

Revision ID: 529452f55a5f
Revises: e0756b5563bf
Create Date: 2026-03-01 13:44:23.721764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '529452f55a5f'
down_revision: Union[str, Sequence[str], None] = 'e0756b5563bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_to_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_to_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subscriber_to_id', name='uq_subscription_pair')
    )
    op.create_index('idx_subscriptions_subscriber_to_id', 'subscriptions', ['subscriber_to_id'], unique=False)
    op.create_index('idx_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscriber_to_id'), 'subscriptions', ['subscriber_to_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_subscriber_to_id'), table_name='subscriptions')
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_subscriber_to_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
