"""Add news

Revision ID: 7bd9760dece7
Revises: 529452f55a5f
Create Date: 2026-05-06 20:17:39.671468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7bd9760dece7'
down_revision: Union[str, Sequence[str], None] = '529452f55a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_user_id'), 'news', ['user_id'], unique=False)
    op.alter_column('comments', 'text',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('posts', 'text',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'text',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('comments', 'text',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_news_user_id'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
