"""Initial revision

Revision ID: a2fa5795f444
Revises: 
Create Date: 2026-02-14 21:01:08.589385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a2fa5795f444'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_hobby',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'hobby_id')
    )
    op.create_table('user_language',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'language_id')
    )
    op.create_table('user_travel_goal',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('travel_goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['travel_goal_id'], ['travel_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'travel_goal_id')
    )
    op.alter_column('hobbies', 'hobby_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=40),
               nullable=False)
    op.create_unique_constraint(None, 'hobbies', ['hobby_name'])
    op.add_column('languages', sa.Column('language_name', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'languages', ['language_name'])
    op.drop_column('languages', 'user_languages')
    op.alter_column('travel_goals', 'travel_goal_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=40),
               nullable=False)
    op.create_unique_constraint(None, 'travel_goals', ['travel_goal_name'])
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('MALE', 'FEMALE', name='gender'),
               nullable=False)
    op.alter_column('users', 'about',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('users', 'header_image_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'avatar_image_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=48),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('users', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=48),
               type_=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'avatar_image_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('users', 'header_image_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('users', 'about',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', name='gender'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'travel_goals', type_='unique')
    op.alter_column('travel_goals', 'travel_goal_name',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.add_column('languages', sa.Column('user_languages', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'languages', type_='unique')
    op.drop_column('languages', 'language_name')
    op.drop_constraint(None, 'hobbies', type_='unique')
    op.alter_column('hobbies', 'hobby_name',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_table('user_travel_goal')
    op.drop_table('user_language')
    op.drop_table('user_hobby')
    # ### end Alembic commands ###
